kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include ".Values.persistentVolumeClaim.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: {{ include ".Values.persistentVolumeClaim.storageClassName" . }}