apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingress-controller.fullname" . }}
  labels:
    {{- include "ingress-controller.labels" . | nindent 4 }}
data:
  yarp.json: |
    {
      "Yarp": {
        "ControllerClass": "netcorepal.io/{{ .Values.controllerClass }}"
      }
    }