apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.controllerClass }}
  labels:
    {{- include "ingress-controller.labels" . | nindent 4 }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "{{ .Values.isDefaultClass }}"
spec:
  controller: netcorepal.io/{{ .Values.controllerClass }}