apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-controller.fullname" . }}
  labels:
    {{- include "ingress-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # - port: {{ .Values.service.port }}
    #   targetPort: http
    #   protocol: TCP
    #   name: http
    - name: proxy
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: proxy
    - name: proxy-ssl
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    {{- include "ingress-controller.selectorLabels" . | nindent 4 }}
